# Task 14: Cluster Recovery - Setup
# This task requires deliberate misconfiguration of the API server
# We can simulate this by creating a broken custom resource
apiVersion: v1
kind: ConfigMap
metadata:
  name: broken-apiserver-settings
  namespace: kube-system
data:
  simulation-info: "This ConfigMap simulates a broken API server configuration. The actual API server would be configured incorrectly with etcd endpoints pointing to the wrong location."